config/routes.rb
Rails.application.routes.draw do
  resources :tweeets do
    collection do
      post :confirm
    end
  end
  root "tweeets#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tweeet.rb
class Tweeet < ApplicationRecord
    validates :content, presence: true
    validates :content,    length: { in: 1..140 }        # 「1 to 75 letters」
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tweeets_controller.rb
class TweeetsController < ApplicationController
  before_action :set_tweeet, only: [:show, :edit, :update, :destroy]

  # GET /tweeets
  # GET /tweeets.json
  def index
    @tweeets = Tweeet.all
  end

  # GET /tweeets/1
  # GET /tweeets/1.json
  def show
  end

  # GET /tweeets/new
  def new
    if params[:back]
      @tweeet = Tweeet.new(tweeet_params)
    else
      
    @tweeet = Tweeet.new
  end
end
  # GET /tweeets/1/edit
  def edit
  end

  # POST /tweeets
  # POST /tweeets.json
  def create
    @tweeet = Tweeet.new(tweeet_params)

    respond_to do |format|
      if @tweeet.save
        format.html { redirect_to @tweeet, notice: 'Tweeet was successfully created.' }
        format.json { render :show, status: :created, location: @tweeet }
      else
        format.html { render :new }
        format.json { render json: @tweeet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tweeets/1
  # PATCH/PUT /tweeets/1.json
  def update
    respond_to do |format|
      if @tweeet.update(tweeet_params)
        format.html { redirect_to @tweeet, notice: 'Tweeet was successfully updated.' }
        format.json { render :show, status: :ok, location: @tweeet }
      else
        format.html { render :edit }
        format.json { render json: @tweeet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweeets/1
  # DELETE /tweeets/1.json
  def destroy
    @tweeet.destroy
    respond_to do |format|
      format.html { redirect_to tweeets_url, notice: 'Tweeet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  def confirm 
    @tweeet = Tweeet.new(tweeet_params)
    render :new if @tweeet.invalid?
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweeet
      @tweeet = Tweeet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tweeet_params
      params.require(:tweeet).permit(:content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweeets_helper.rb
module TweeetsHelper
    def choose_new_or_edit
        if action_name =='new' ||action_name == 'confirm'
            confirm_tweeets_path
        elsif action_name == 'edit'
                tweeet_path
        end
    end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TwittterAssign</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body>
  <header class="header">
  <div class="container">
    <nav class="level">
      <div class="level-left">
        <div class="level-item">
          WELCOME TO TWITTER   <%= link_to image_tag("download.png",width:70 ,height:80)%>

        </div>
      </div>
      <div class="level-right">
        <p class="level-item">
          <%= link_to("SIGN UP", tweeets_path, :class => "button is-dark is-outlined") %>
        </p>
        <p class="level-item">
          <%= link_to("LOGIN", tweeets_path, :class => "button is-dark is-outlined") %>
        </p>
        
        
      </div>
    </nav>
  </div>
</header>
<section class="section">
  <div class="container">
    <%= yield %>
  </div>
</section>
<footer class="footer">
  <div class="container">
    Copyright © 2019 Cherif chervis_TWITTER. All rights reserved.
  </div>
</footer>
    
  </body>
</html>

app/views/tweeets/_form.html.erb
<%= form_with(model: @tweeet, local: true,url: choose_new_or_edit) do |form| %>

  <% if @tweeet.errors.any? %>
    <div id="error_explanation">
      <h2><%= @tweeet.errors.count %>errors occurred.</h2>
      <ul>

      <% @tweeet.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :content%>
    <%= form.text_area :content %>
    
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tweeets/confirm.html.erb
<h1>CONFIRMATION</h1>

<%= form_with(model: @tweeet,url:tweeets_path,local: true)do |form|%>
<%= form.hidden_field :content%>



<p>Body:<%= @tweeet.content %></p>
  <%= form.submit  "submit" %>
<% end %>

<%= form_with(model: @tweeet, url: new_tweeet_path, method: 'get') do |form| %>
  <%= form.hidden_field :content %>
<%= link_to 'Back', tweeets_path %>

<% end %>

app/views/tweeets/edit.html.erb
<h1>Editing Tweeet</h1>
<hr>
<%= render 'form', tweeet: @tweeet %>

<%= link_to 'Show', @tweeet %> |
<%= link_to 'Back', tweeets_path %>

app/views/tweeets/index.html.erb
<p id="notice"><%= notice %></p>

<strong>All Tweets</strong>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th colspan="3">Actions</th>
    </tr>
    <hr>
  </thead>

  <tbody>
    <% @tweeets.each do |tweeet| %>
      <tr>
        <td><%= tweeet.content %></td>
        <td><%= link_to 'Show', tweeet %></td>
        <td><%= link_to 'Edit', edit_tweeet_path(tweeet),data: { confirm: 'Are you sure?' }%></td>
        <td><%= link_to 'Destroy', tweeet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tweet', new_tweeet_path %>

app/views/tweeets/new.html.erb
<h1>New Tweet</h1>
<hr>

<%= render 'form', tweeet: @tweeet %>

<%= link_to 'Back', tweeets_path %>

app/views/tweeets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @tweeet.content %>
</p>

<%= link_to 'Edit', edit_tweeet_path(@tweeet) %> |
<%= link_to 'Back', tweeets_path %>